### ISSUE TITLE
Initials accuracy for multi-word surnames

### ISSUE THREAD

**Issue by zane-programs** [SambhavG/mp#1]
Hello! Very cool project you've got here :) I'm not on campus this quarter, and thus didn't do Marriage Pact, but happened upon your project via Fizz.

Out of curiosity, I put my initials in (ZS) and didn't see my name on the list (my last name is St. John). However, I came up when I searched ZJ. Reviewing the implementation, I see that the surname initial was computed using the last "word" in someone's full name.

I'm not sure how you grabbed the data, but I think rich name data is available some places (e.g. https://profiles.stanford.edu/proxy/api/cap/search/keyword?q=sambhav). I'm guessing you came up with an elegant-ish way to scrape all of this data.

Thanks for this putting together this cool project!

**Comment by SambhavG** [comment]
Yeah it just uses the last word splitting on spaces. I don't see a way to distinguish between multiword surnames and middle names from the API link you gave (which is the one I used). Probably not going to try to fix this as the project itself will be stale in a couple days.

<img width="754" alt="Screenshot 2024-11-15 at 11 41 00 AM" src="https://github.com/user-attachments/assets/3ff712e6-7416-4c0d-9472-a9b51376e9a4">

**Comment by zane-programs** [comment]
It should be there, but you're right that there's not much need to fix, as the project will be stale soon. Sorry to bother you, and have a good one!

<img width="582" alt="Screenshot 2024-11-15 at 11 47 58 AM" src="https://github.com/user-attachments/assets/cf65728b-a648-44e8-babf-f8395fc8bfc2">

**Comment by SambhavG** [comment]
Ah my bad, I was looking at the other list (ui, not data) so didn't see it
